services:
  mariadb:
    image: 8ct8pus/mariadb-alpine:1.1.1
    container_name: classicpress-db
    ports:
      - 3306:3306
    volumes:
      # expose mariadb config to host
      - ./docker/etc/:/docker/etc/
      # save mariadb databases to named volume
      - database:/var/lib/mysql/
  web:
    # php 8.4.8
    image: 8ct8pus/apache-php-fpm-alpine:2.5.1
    hostname: classicpress
    container_name: classicpress
    ports:
      - 80:80
      - 443:443
      - 8025:8025
    environment:
      - DOMAIN=localhost
      - DOCUMENT_ROOT=/public
    links:
      - mariadb
    volumes:
      # development directory
      - ./sites/:/sites/
      # expose apache2 and php config to host
      - ./docker/etc/:/docker/etc/
volumes:
  database:
