<?php

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';

/** @disregard P1011 */
if (!defined('WP_SHOW_DEPRECATIONS') || WP_SHOW_DEPRECATIONS === false) {
    if (function_exists('add_filter')) {
        // hide classicpress jquery-ui deprecations
        add_filter('deprecated_argument_trigger_error', '__return_false');
    }
}
